name: Cena
view:
    - [ 0.0, 0.0, 3.0 ]
    - [ 0.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
projection:
    angle: 45.0
    frustrum: [ 0.1, 100.0]
light:
    pos: [ -20.0, 20.0, -5.0 ]
    color: [ 1.0, 1.0, 1.0 ]
objects:
    -   name: Terra
        obj-file: ../3D_Models/Vivencial/Terra.obj
        pos: [ 0, 0, -3 ]
        angle: 0
        scale: [ 0.5, 0.5, 0.5 ]
        animation:
            - [ 0.0, 0.0, -3.0 ]
            - [ 0.0, 2.0, -3.0 ]
            - [ 2.0, 2.0, -3.0 ]
            - [ 2.0, 0.0, -3.0 ]
    -   name: Mercurio
        obj-file: ../3D_Models/Vivencial/Mercurio.obj
        pos: [ -2, 0, -3 ]
        angle: 0
        scale: [ 0.5, 0.5, 0.5 ]
    -   name: Suzanne
        obj-file: ../3D_Models/Vivencial/SuzanneTriTextured.obj
        pos: [ 2, 0, -3 ]
        angle: 0
        scale: [ 0.5, 0.5, 0.5 ]
    -   name: Cube
        obj-file: ../3D_Models/Vivencial/cube.obj
        pos: [ 2, 2, -3 ]
        angle: 0
        scale: [ 0.5, 0.5, 0.5 ]